sculpin_content_types:
    posts:
        path: _posts/**
        permalink: :year/:month/:filename.html
services:
    twig.extension.intl-extra:
        class: Twig\Extra\Intl\IntlExtension
        tags:
            - { name: twig.extension }
    twig.extension.pcre:
        class: Jasny\Twig\PcreExtension
        tags:
            - { name: twig.extension }
    twig.extension.tags:
        class: Falvarez\Blog\TagsExtension
        tags:
            - { name: twig.extension }
    twig.extension.lcfirst:
        class: Falvarez\Blog\LcfirstExtension
        tags:
            - { name: twig.extension }
parameters:
    locale: "es_ES"
    timezone: "Europe/Madrid"
