sculpin_content_types:
    posts:
        permalink: :year/:month/:filename.html
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
parameters:
    locale: "es_ES"
    timezone: "Europe/Madrid"